
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Vehicle vehicleA = new Vehicle("XaXa", "falali");
        Vehicle vehicleB = new Vehicle("Eddie", "Jacky");

        vehicleA.speedUp(30);
        vehicleB.speedUp(40);

        Car car = new Car ("My Car", "Goodby");
        car.speedUp(180);
        car.speedUp(201);

        Vehicle bus = new Bus("my bus", "OOCL");
        bus.speedUp(70);
        bus.speedUp(100);

        Driver tommy = new Driver(vehicleA, "tommy");
        tommy.speedUp(50);

        Driver jacky = new Driver(car, "Jacky");
        jacky.speedUp(111);

        Driver baby = new Driver(bus, "Baby");
        baby.speedUp(666);
    }
}

class Driver {
    private final Vehicle vehicle;
    private final String name;

    public Driver(Vehicle vehicle, String name) {
        this.vehicle = vehicle;
        this.name = name;
    }

    public void speedUp(int speed) {
        System.out.print("Name: " + this.name);
        this.vehicle.speedUp(speed);
    }
}

class Bus extends Vehicle {
    public Bus(String name, String brand) {
        super(name, brand);
    }

    @Override
    public void speedUp(int speed) {
        if(speed > 80){
            System.out.print("Too Fast!!!!!!");
        }else{
            super.speedUp(speed);
        }
    }
}

class Car extends Vehicle {
    public Car(String name, String brand) {
        super(name, brand);
    }

    @Override
    public void speedUp(int speed) {
        if(speed > 190){
            System.out.print("Too Fast!!!!!!");
        }else{
            super.speedUp(speed);
        }
    }
}

class Vehicle {
    private String name;
    private String brand;

    public Vehicle (String name, String brand){
        this.name = name;
        this.brand = brand;
    }


    public void speedUp(int speed) {
        System.out.print("Name: " + this.name + " Brand: " + this.brand +  "speed up to " + speed);
    }
}
